/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-03T09:39:45.148889300+08:00[GMT+08:00]", comments = "Generator version: 7.13.0")
@Validated
@Tag(name = "数据统计", description = "the 数据统计 API")
public interface AnalyticsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /analytics/monthly_report : 获取月度统计
     * 获取月度学习统计
     *
     * @param month :指定月份，格式 YYYY-MM，默认为当前月 (optional)
     * @return  (status code 200)
     */
    @Operation(
        operationId = "analyticsMonthlyReportGet",
        summary = "获取月度统计",
        description = "获取月度学习统计",
        tags = { "数据统计" },
        responses = {
            @ApiResponse(responseCode = "200", description = "", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearer")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/analytics/monthly_report",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Object> analyticsMonthlyReportGet(
        @Parameter(name = "month", description = ":指定月份，格式 YYYY-MM，默认为当前月", in = ParameterIn.QUERY) @Valid @RequestParam(value = "month", required = false) String month
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /analytics/weekly_report : 获取学习报告
     * 获取本周学习数据统计
     *
     * @param week 指定周数，格式 YYYY-MM-DD，默认为当前周 (optional)
     * @return  (status code 200)
     */
    @Operation(
        operationId = "analyticsWeeklyReportGet",
        summary = "获取学习报告",
        description = "获取本周学习数据统计",
        tags = { "数据统计" },
        responses = {
            @ApiResponse(responseCode = "200", description = "", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearer")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/analytics/weekly_report",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Object> analyticsWeeklyReportGet(
        @Parameter(name = "week", description = "指定周数，格式 YYYY-MM-DD，默认为当前周", in = ParameterIn.QUERY) @Valid @RequestParam(value = "week", required = false) String week
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
