/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-03T09:39:45.148889300+08:00[GMT+08:00]", comments = "Generator version: 7.13.0")
@Validated
@Tag(name = "课程管理", description = "the 课程管理 API")
public interface CoursesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * DELETE /courses/{course_id} : 删除课程
     * 删除课程
     *
     * @param courseId  (required)
     * @param body  (required)
     * @return  (status code 200)
     */
    @Operation(
        operationId = "coursesCourseIdDelete",
        summary = "删除课程",
        description = "删除课程",
        tags = { "课程管理" },
        responses = {
            @ApiResponse(responseCode = "200", description = "", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearer")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/courses/{course_id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Object> coursesCourseIdDelete(
        @Parameter(name = "course_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("course_id") String courseId,
        @Parameter(name = "body", description = "", required = true) @Valid @RequestBody Object body
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /courses/{course_id} : 获取课程详情
     * 获取课程详细信息
     *
     * @param courseId  (required)
     * @param body  (required)
     * @param 课程  (optional)
     * @param 任课老师  (optional)
     * @param 地点  (optional)
     * @param 起始周  (optional)
     * @param 结束周  (optional)
     * @return  (status code 200)
     */
    @Operation(
        operationId = "coursesCourseIdGet",
        summary = "获取课程详情",
        description = "获取课程详细信息",
        tags = { "课程管理" },
        responses = {
            @ApiResponse(responseCode = "200", description = "", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearer")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/courses/{course_id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Object> coursesCourseIdGet(
        @Parameter(name = "course_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("course_id") String courseId,
        @Parameter(name = "body", description = "", required = true) @Valid @RequestBody Object body,
        @Parameter(name = "课程", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "课程", required = false) String 课程,
        @Parameter(name = "任课老师", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "任课老师", required = false) String 任课老师,
        @Parameter(name = "地点", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "地点", required = false) String 地点,
        @Parameter(name = "起始周", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "起始周", required = false) String 起始周,
        @Parameter(name = "结束周", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "结束周", required = false) String 结束周
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /courses : 获取课程列表
     * 获取当前用户的所有课程
     *
     * @param page 页数，从1开始 (required)
     * @param body  (required)
     * @param pageSize 每页数量，默认10 (optional)
     * @return  (status code 200)
     */
    @Operation(
        operationId = "coursesGet",
        summary = "获取课程列表",
        description = "获取当前用户的所有课程",
        tags = { "课程管理" },
        responses = {
            @ApiResponse(responseCode = "200", description = "", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearer")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/courses",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Object> coursesGet(
        @NotNull @Parameter(name = "page", description = "页数，从1开始", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = true) Integer page,
        @Parameter(name = "body", description = "", required = true) @Valid @RequestBody Object body,
        @Parameter(name = "pageSize", description = "每页数量，默认10", in = ParameterIn.QUERY) @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /courses : 创建课程
     * 创建新课程
     *
     * @param body  (required)
     * @param 课程名称  (optional)
     * @param 地点  (optional)
     * @param 任课老师  (optional)
     * @param 起始周  (optional)
     * @param 结束周  (optional)
     * @param 星期  (optional)
     * @param 起始时间  (optional)
     * @param 结束时间  (optional)
     * @return  (status code 200)
     */
    @Operation(
        operationId = "coursesPost",
        summary = "创建课程",
        description = "创建新课程",
        tags = { "课程管理" },
        responses = {
            @ApiResponse(responseCode = "200", description = "", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearer")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/courses",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Object> coursesPost(
        @Parameter(name = "body", description = "", required = true) @Valid @RequestBody Object body,
        @Parameter(name = "课程名称", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "课程名称", required = false) String 课程名称,
        @Parameter(name = "地点", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "地点", required = false) String 地点,
        @Parameter(name = "任课老师", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "任课老师", required = false) String 任课老师,
        @Parameter(name = "起始周", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "起始周", required = false) String 起始周,
        @Parameter(name = "结束周", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "结束周", required = false) String 结束周,
        @Parameter(name = "星期", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "星期", required = false) String 星期,
        @Parameter(name = "起始时间", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "起始时间", required = false) String 起始时间,
        @Parameter(name = "结束时间", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "结束时间", required = false) String 结束时间
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
