/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import java.math.BigDecimal;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-03T09:39:45.148889300+08:00[GMT+08:00]", comments = "Generator version: 7.13.0")
@Validated
@Tag(name = "专注计时", description = "the 专注计时 API")
public interface FocusSessionsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /focus_sessions : 获取专注记录列表
     * 获取用户的专注记录
     *
     * @param body  (required)
     * @param taskId 按任务筛选 (optional)
     * @param startDate 开始日期 (optional)
     * @param endDate 结束日期 (optional)
     * @param page 页码 (optional)
     * @param pageSize 每页数量 (optional)
     * @return  (status code 200)
     */
    @Operation(
        operationId = "focusSessionsGet",
        summary = "获取专注记录列表",
        description = "获取用户的专注记录",
        tags = { "专注计时" },
        responses = {
            @ApiResponse(responseCode = "200", description = "", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearer")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/focus_sessions",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Object> focusSessionsGet(
        @Parameter(name = "body", description = "", required = true) @Valid @RequestBody Object body,
        @Parameter(name = "taskId", description = "按任务筛选", in = ParameterIn.QUERY) @Valid @RequestParam(value = "taskId", required = false) String taskId,
        @Parameter(name = "startDate", description = "开始日期", in = ParameterIn.QUERY) @Valid @RequestParam(value = "startDate", required = false) String startDate,
        @Parameter(name = "endDate", description = "结束日期", in = ParameterIn.QUERY) @Valid @RequestParam(value = "endDate", required = false) String endDate,
        @Parameter(name = "page", description = "页码", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false) Integer page,
        @Parameter(name = "pageSize", description = "每页数量", in = ParameterIn.QUERY) @Valid @RequestParam(value = "pageSize", required = false) String pageSize
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /focus_sessions : 创建专注记录
     * 记录专注会话
     *
     * @param taskId 关联的任务ID (required)
     * @param minutes 专注时长（分钟） (required)
     * @param startTime 开始时间 (required)
     * @param body  (required)
     * @param note 备注 (optional)
     * @return  (status code 200)
     */
    @Operation(
        operationId = "focusSessionsPost",
        summary = "创建专注记录",
        description = "记录专注会话",
        tags = { "专注计时" },
        responses = {
            @ApiResponse(responseCode = "200", description = "", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearer")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/focus_sessions",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Object> focusSessionsPost(
        @NotNull @Parameter(name = "taskId", description = "关联的任务ID", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "taskId", required = true) BigDecimal taskId,
        @NotNull @Parameter(name = "minutes", description = "专注时长（分钟）", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "minutes", required = true) BigDecimal minutes,
        @NotNull @Parameter(name = "startTime", description = "开始时间", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "startTime", required = true) String startTime,
        @Parameter(name = "body", description = "", required = true) @Valid @RequestBody Object body,
        @Parameter(name = "note", description = "备注", in = ParameterIn.QUERY) @Valid @RequestParam(value = "note", required = false) String note
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
