/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-03T09:39:45.148889300+08:00[GMT+08:00]", comments = "Generator version: 7.13.0")
@Validated
@Tag(name = "专注计时", description = "the 专注计时 API")
public interface StudyApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /study : 学习报告
     * 
     *
     * @param 专注时长  (required)
     * @param 任务数量  (optional)
     * @param 专注效率  (optional)
     * @param 环状图  (optional)
     * @param 环状图里专注时间  (optional)
     * @return  (status code 200)
     */
    @Operation(
        operationId = "studyGet",
        summary = "学习报告",
        description = "",
        tags = { "专注计时" },
        responses = {
            @ApiResponse(responseCode = "200", description = "", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/study",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Object> studyGet(
        @NotNull @Parameter(name = "专注时长", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "专注时长", required = true) Integer 专注时长,
        @Parameter(name = "任务数量", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "任务数量", required = false) String 任务数量,
        @Parameter(name = "专注效率", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "专注效率", required = false) String 专注效率,
        @Parameter(name = "环状图", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "环状图", required = false) String 环状图,
        @Parameter(name = "环状图里专注时间", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "环状图里专注时间", required = false) String 环状图里专注时间
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
