/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-03T09:39:45.148889300+08:00[GMT+08:00]", comments = "Generator version: 7.13.0")
@Validated
@Tag(name = "任务管理", description = "the 任务管理 API")
public interface TasksApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /tasks : 添加作业
     * 获取用户的任务列表
     *
     * @param 是否拆解  (required)
     * @param body  (required)
     * @param 作业名 按课程筛选 (optional)
     * @param 状态 按状态筛选 (optional)
     * @param 起始时间 按优先级筛选 (optional)
     * @param 截止时间 页码 (optional)
     * @return  (status code 200)
     */
    @Operation(
        operationId = "tasksGet",
        summary = "添加作业",
        description = "获取用户的任务列表",
        tags = { "任务管理" },
        responses = {
            @ApiResponse(responseCode = "200", description = "", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearer")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/tasks",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Object> tasksGet(
        @NotNull @Parameter(name = "是否拆解", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "是否拆解", required = true) Boolean 是否拆解,
        @Parameter(name = "body", description = "", required = true) @Valid @RequestBody Object body,
        @Parameter(name = "作业名", description = "按课程筛选", in = ParameterIn.QUERY) @Valid @RequestParam(value = "作业名", required = false) String 作业名,
        @Parameter(name = "状态", description = "按状态筛选", in = ParameterIn.QUERY) @Valid @RequestParam(value = "状态", required = false) String 状态,
        @Parameter(name = "起始时间", description = "按优先级筛选", in = ParameterIn.QUERY) @Valid @RequestParam(value = "起始时间", required = false) String 起始时间,
        @Parameter(name = "截止时间", description = "页码", in = ParameterIn.QUERY) @Valid @RequestParam(value = "截止时间", required = false) String 截止时间
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /tasks : 创建任务
     * 创建新任务
     *
     * @param body  (required)
     * @return  (status code 200)
     */
    @Operation(
        operationId = "tasksPost",
        summary = "创建任务",
        description = "创建新任务",
        tags = { "任务管理" },
        responses = {
            @ApiResponse(responseCode = "200", description = "", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearer")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/tasks",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Object> tasksPost(
        @Parameter(name = "body", description = "", required = true) @Valid @RequestBody Object body
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /tasks/{taskId}/breakdown : 智能拆解任务
     * 将大任务拆解为每日子任务
     *
     * @param taskId  (required)
     * @param body  (required)
     * @return  (status code 200)
     */
    @Operation(
        operationId = "tasksTaskIdBreakdownPost",
        summary = "智能拆解任务",
        description = "将大任务拆解为每日子任务",
        tags = { "智能任务拆解" },
        responses = {
            @ApiResponse(responseCode = "200", description = "", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearer")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/tasks/{taskId}/breakdown",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Object> tasksTaskIdBreakdownPost(
        @Parameter(name = "taskId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("taskId") String taskId,
        @Parameter(name = "body", description = "", required = true) @Valid @RequestBody Object body
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /tasks/{taskId} : 删除任务
     * 删除任务
     *
     * @param taskId  (required)
     * @param body  (required)
     * @return  (status code 200)
     */
    @Operation(
        operationId = "tasksTaskIdDelete",
        summary = "删除任务",
        description = "删除任务",
        tags = { "任务管理" },
        responses = {
            @ApiResponse(responseCode = "200", description = "", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearer")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/tasks/{taskId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Object> tasksTaskIdDelete(
        @Parameter(name = "taskId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("taskId") String taskId,
        @Parameter(name = "body", description = "", required = true) @Valid @RequestBody Object body
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /tasks/{taskId} : 获取任务详情
     * 获取任务详细信息
     *
     * @param taskId  (required)
     * @param 名字  (optional)
     * @param 时间  (optional)
     * @param 图片  (optional)
     * @return  (status code 200)
     */
    @Operation(
        operationId = "tasksTaskIdGet",
        summary = "获取任务详情",
        description = "获取任务详细信息",
        tags = { "任务管理" },
        responses = {
            @ApiResponse(responseCode = "200", description = "", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearer")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/tasks/{taskId}",
        produces = { "application/json" },
        consumes = { "multipart/form-data" }
    )
    
    default ResponseEntity<Object> tasksTaskIdGet(
        @Parameter(name = "taskId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("taskId") String taskId,
        @Parameter(name = "名字", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "名字", required = false) String 名字,
        @Parameter(name = "时间", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "时间", required = false) String 时间,
        @Parameter(name = "图片", description = "") @RequestPart(value = "图片", required = false) MultipartFile 图片
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /tasks/{taskId} : 更新任务
     * 
     *
     * @param taskId  (required)
     * @param body  (required)
     * @return  (status code 200)
     */
    @Operation(
        operationId = "tasksTaskIdPut",
        summary = "更新任务",
        description = "",
        tags = { "任务管理" },
        responses = {
            @ApiResponse(responseCode = "200", description = "", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearer")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/tasks/{taskId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Object> tasksTaskIdPut(
        @Parameter(name = "taskId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("taskId") String taskId,
        @Parameter(name = "body", description = "", required = true) @Valid @RequestBody Object body
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /tasks/{taskId}/subtasks : 获取子任务列表
     * 获取任务的子任务列表
     *
     * @param taskId  (required)
     * @param body  (required)
     * @return  (status code 200)
     */
    @Operation(
        operationId = "tasksTaskIdSubtasksGet",
        summary = "获取子任务列表",
        description = "获取任务的子任务列表",
        tags = { "智能任务拆解" },
        responses = {
            @ApiResponse(responseCode = "200", description = "", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearer")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/tasks/{taskId}/subtasks",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Object> tasksTaskIdSubtasksGet(
        @Parameter(name = "taskId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("taskId") String taskId,
        @Parameter(name = "body", description = "", required = true) @Valid @RequestBody Object body
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
